# Generated by Django 3.0.2 on 2020-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='instructor',
            new_name='name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='photo_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
